name: iOS Unit tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "jb-main"

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  unit-tests-uikit:
    runs-on: macos-13
    name: iOS UIKit tests (MacOS-13)
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: install Android SDK
        run: ./jbdeps/android-sdk/downloadAndroidSdk
      - name: Run UIKit tests
        run: ./gradlew :mpp:testUIKit --info
      - name: Generate report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: iOS UIKit tests results
          path: out/androidx/compose/**/**/build/test-results/**/TEST*.xml
          reporter: java-junit
  unit-tests-cmp-utils:
    runs-on: macos-13
    name: iOS CMP Utils tests (MacOS-13)
    steps:
      - uses: actions/checkout@v3
      - name: Run CMPUIKitUtilsTests
        working-directory: compose/ui/ui-uikit/src/uikitMain/objc/CMPUIKitUtils
        run: xcodebuild test -scheme CMPUIKitUtilsTests -project CMPUIKitUtils.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15' -resultBundlePath CMPUIKitUtilsTests.xcresult
      - name: Generate report
        uses: kishikawakatsumi/xcresulttool@v1
        if: always()
        with:
          title: iOS CMP Utils tests results
          path: 'compose/ui/ui-uikit/src/uikitMain/objc/CMPUIKitUtils/CMPUIKitUtilsTests.xcresult'
          reporter: java-junit
