name: iOS Unit tests
on:
  pull_request:
  #push: #todo remove when tests will be completed

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: macos-13
    name: iOS Unit tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - id: run_tests
        run: ./gradlew :mpp:testUIKit
