name: iOS Unit tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "jb-main"
      - "dima-andrei/ios-tests-on-pr" #TODO remove

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: macos-13
    name: iOS Unit tests on MacOS-13
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: install Android SDK
        run: ./jbdeps/android-sdk/downloadAndroidSdk
      - name: Run UIKit tests
        run: ./gradlew :mpp:testUIKit --info
      - name: Generate report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUNIT Tests
          path: test-results/uikitSimArm64Test/TEST-*.xml
          reporter: java-junit
