name: iOS Unit tests
on:
  pull_request:
  push:
    branches: 
      - "jb-main"
      - "dima-andrei/ios-tests-on-pr-3"


concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: macos-13
    name: iOS Unit tests on MacOS-13
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - id: run_tests
        run: ./gradlew :mpp:testUIKit

  unit-tests-2:
    runs-on: macos-latest
    name: iOS Unit tests on MacOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - id: run_tests
        run: ./gradlew :mpp:testUIKit
